
title: Test blog site
email: xepozz@list.ru
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/gp" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: xepozz
github_username:  xepozz

# Build settings
markdown: kramdown
theme: minima
#remote_theme: jekyll/minima

minima:
  skin: classic
  # skin: dark
  # skin: solarized-dark
  date_format: "%a, %b %-d, %Y (week %V)"
  social_links:
    twitter: xepozz
    github: xepozz
    linkedin: xepozz
    facebook: xepozz

show_excerpts: true
excerpt_separator: <!--cut-->

plugins:
  - github-pages-health-check
  - jekyll
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-swiss
  - jekyll-titles-from-headings
  - jemoji
  - kramdown
  - kramdown-parser-gfm
  - liquid
  - mercenary
  - minima
  - rouge

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
